version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-fixed-behat.yml

env:
  global:
    - COMPOSER_ROOT_VERSION="4.7.x-dev"
    - REQUIRE_RECIPE="$COMPOSER_ROOT_VERSION"
    - BEHAT_SUITE=siteconfig
