---
Name: rootroutes
---
SilverStripe\Control\Director:
  rules:
    '': SilverStripe\Control\Controller
---
Name: coreroutes
After:
  - '#rootroutes'
---
SilverStripe\Control\Director:
  rules:
    'Security//$Action/$ID/$OtherID': SilverStripe\Security\Security
    'CMSSecurity//$Action/$ID/$OtherID': SilverStripe\Security\CMSSecurity
    'dev': SilverStripe\Dev\DevelopmentAdmin
---
Name: security-limited
Before:
  - '#coreroutes'
Except:
  environment: dev
---
SilverStripe\Control\Director:
  rules:
    'POST Security//$Action/$ID/$OtherID': '%$RateLimitedSecurityController'
