name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Tuesday at 2:20pm UTC
  schedule:
    - cron: '20 14 * * 2'

jobs:
  ci:
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
